In [1]:
import pandas as pd
import numpy as np

In [5]:
retail_sales_data = pd.read_csv("Fashion_Retail_Sales.csv")
retail_sales_data.head()

,Customer Reference ID,Item Purchased,Purchase Amount (USD),Date Purchase,Review Rating,Payment Method
0,4018,Handbag,4619.0,2023-02-05,NaN,Credit Card
1,4115,Tunic,2456.0,2023-07-11,2.0,Credit Card
2,4019,Tank Top,2102.0,2023-03-23,4.1,Cash
3,4097,Leggings,3126.0,2023-03-15,3.2,Cash
4,3997,Wallet,3003.0,2022-11-27,4.7,Cash

In [20]:
inventory_data = pd.read_csv("retail_store_inventory_data.csv")
inventory_data.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [21]:
inventory_data.shape

(73100, 15)

In [23]:
inventory_data.columns = inventory_data.columns.str.lower().str.replace(" ", "_")
inventory_data.head()

,date,store_id,product_id,category,region,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,weather_condition,holiday/promotion,competitor_pricing,seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [24]:
type(inventory_data)

pandas.core.frame.DataFrame

In [25]:
inventory_data['date'] = pd.to_datetime(inventory_data['date'])

In [26]:
inventory_data = inventory_data.sort_values(['product_id', 'date'])

In [27]:
inventory_data

,date,store_id,product_id,category,region,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,weather_condition,holiday/promotion,competitor_pricing,seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
20,2022-01-01,S002,P0001,Groceries,South,343,104,144,112.55,32.80,20,Sunny,1,30.78,Spring
40,2022-01-01,S003,P0001,Toys,South,241,147,180,161.09,67.21,5,Sunny,1,67.39,Summer
60,2022-01-01,S004,P0001,Toys,South,477,271,66,286.65,15.62,15,Sunny,0,16.09,Winter
80,2022-01-01,S005,P0001,Toys,West,111,77,60,83.47,70.33,10,Cloudy,0,70.29,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73019,2024-01-01,S001,P0020,Electronics,South,242,52,198,50.82,11.00,0,Rainy,0,7.46,Spring
73039,2024-01-01,S002,P0020,Groceries,East,284,225,172,222.74,75.94,20,Cloudy,0,79.53,Winter
73059,2024-01-01,S003,P0020,Groceries,West,417,277,148,285.80,54.19,0,Cloudy,1,55.64,Spring
73079,2024-01-01,S004,P0020,Toys,West,249,243,115,248.08,32.87,20,Sunny,0,31.39,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [ ]:
inventory_data